<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">splitUrl</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required url</value>
    <value>[o] field:0:required owner</value>
    <value>[o] field:0:required repo</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyB1cmwgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29y
LCAidXJsIiApOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgovLyBwcm9jZXNzCgpTdHJpbmcg
b3duZXIgPSBudWxsOwpTdHJpbmcgcmVwbyA9IG51bGw7CgppZiAodXJsICE9IG51bGwpIHsKClN0
cmluZ1tdIHBhcnRzID0gc3BsaXRVcmkodXJsKTsKb3duZXIgPSBwYXJ0c1swXTsKcmVwbyA9IHBh
cnRzWzFdOwoKdHJ5IHsKVVJMIHVybFBhcnNlZCA9IG5ldyBVUkwodXJsKTsKU3RyaW5nIGdpdGh1
YkFwaUhvc3QgPSAiYXBpLmdpdGh1Yi5jb20iOwpTdHJpbmcgcmVwb0hvc3QgPSB1cmxQYXJzZWQu
Z2V0SG9zdCgpOwppZiAoIShyZXBvSG9zdC5jb250YWlucygiZ2l0aHViLmNvbSIpKSkgewpnaXRo
dWJBcGlIb3N0ID0gU3RyaW5nLmZvcm1hdCgiJXMvYXBpL3YzIiwgcmVwb0hvc3QpOwp9CgpKb3Vy
bmFsTG9nZ2VyLmxvZyg0LDkwLDMsIltXUE1dIiwgIlNlbGVjdGVkIEdpdGh1YiBSRVNUIEFQSSBo
b3N0OiAiICsgZ2l0aHViQXBpSG9zdCk7CgovLyBwaXBlbGluZSBvdXQKSURhdGFVdGlsLnB1dChw
aXBlbGluZUN1cnNvciwgImdpdGh1YkFwaUhvc3QiLCBnaXRodWJBcGlIb3N0KTsKSURhdGFVdGls
LnB1dChwaXBlbGluZUN1cnNvciwgInJlcG9Ib3N0IiwgcmVwb0hvc3QpOwp9IGNhdGNoIChNYWxm
b3JtZWRVUkxFeGNlcHRpb24gZSkgewpJRGF0YSBpbnB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUo
KTsKSURhdGFDdXJzb3IgaW5wdXRDdXJzb3IgPSBpbnB1dC5nZXRDdXJzb3IoKTsKSURhdGFVdGls
LnB1dChpbnB1dEN1cnNvciwgImV4Y2VwdGlvbiIsIGUpOwpJRGF0YVV0aWwucHV0KGlucHV0Q3Vy
c29yLCAic3RhY2t0cmFjZSIsIGUuZ2V0U3RhY2tUcmFjZSgpKTsKaW5wdXRDdXJzb3IuZGVzdHJv
eSgpOwpsb2dFeGNlcHRpb24oaW5wdXQpOwoKdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlVu
YWJsZSB0byBjb25zdHJ1Y3QgR2l0SHViIEFQSSBVUkwuIik7Cn0KfQoKLy8gcGlwZWxpbmUgb3V0
CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAib3duZXIiLCBvd25lcik7CklEYXRhVXRp
bC5wdXQocGlwZWxpbmVDdXJzb3IsICJyZXBvIiwgcmVwbyk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTsK</value>
</Values>
