<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">hackForExtractClaims</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7Ck9iamVjdCBjbGFpbXMgPSBJRGF0YVV0aWwuZ2V0KHBpcGVsaW5lQ3Vyc29yLCAi
Y2xhaW1zRGV0YWlscyIpOwpTdHJpbmcgcmVmID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGlu
ZUN1cnNvciwgInJlZiIpOwoKLy8gcHJvY2VzcwoKU3RyaW5nIHZhbHVlID0gbnVsbDsKCmlmIChj
bGFpbXMgaW5zdGFuY2VvZiBJRGF0YSkgewoJIElEYXRhQ3Vyc29yIGMgPSAoKElEYXRhKSBjbGFp
bXMpLmdldEN1cnNvcigpOwoJIHZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCByZWYpOwoJ
IGMuZGVzdHJveSgpOwp9IGVsc2UgewoJSURhdGFbXSB0ZXN0ID0gKElEYXRhW10pIGNsYWltczsK
CWZvciAoaW50IGk9MDsgaTx0ZXN0Lmxlbmd0aDsgaSsrKSB7CgkJCgkJLy9JRGF0YUN1cnNvciBk
YyA9IHRlc3RbaV0uZ2V0Q3Vyc29yKCk7CgkgCS8vU3lzdGVtLm91dC5wcmludGxuKCIiICsgaSAr
ICIgLSAiICsgdGVzdFtpXS50b1N0cmluZygpKTsKCSAJSURhdGFNYXAgZG0gPSBuZXcgSURhdGFN
YXAodGVzdFtpXSk7CgkgCWlmIChkbS5nZXQoIm5hbWUiKS5lcXVhbHMocmVmKSkgewoJIAkJdmFs
dWUgPSAoU3RyaW5nKSBkbS5nZXQoInZhbHVlIik7CgkgCX0KCX0KfQoKLy8gcGlwZWxpbmUgb3V0
CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAidmFsdWUiLCB2YWx1ZSk7CnBpcGVsaW5l
Q3Vyc29yLmRlc3Ryb3koKTsKCQ==</value>
</Values>
