<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">cloneGitRepo</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required uri</value>
    <value>[i] field:0:optional repoName</value>
    <value>[i] field:0:optional tag</value>
    <value>[i] field:0:optional user</value>
    <value>[i] field:0:optional password</value>
    <value>[i] field:0:required localDir</value>
    <value>[i] field:0:optional privateKeyFile</value>
    <value>[i] field:0:optional passPhrase</value>
    <value>[i] record:0:optional auth</value>
    <value>[i] - field:0:optional type</value>
    <value>[i] - field:0:optional user</value>
    <value>[i] - field:0:optional pass</value>
    <value>[i] - field:0:optional delegation {"none","kerberos"}</value>
    <value>[i] - field:0:optional token</value>
    <value>[i] - record:0:optional kerberos</value>
    <value>[i] -- field:0:optional jaasContext</value>
    <value>[i] -- field:0:optional clientPrincipal</value>
    <value>[i] -- field:0:optional clientPassword</value>
    <value>[i] -- field:0:optional servicePrincipal</value>
    <value>[i] -- field:0:optional servicePrincipalForm</value>
    <value>[i] -- field:0:optional requestDelegatableToken {"true","false"}</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigp
OwpTdHJpbmcgdXJpID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJ1cmkiKTsKU3RyaW5n
IHJlcG8gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgInJlcG9OYW1lIik7ClN0cmluZyB0
YWcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgInRhZyIpOwpTdHJpbmcgdXNlciA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAidXNlciIpOwpTdHJpbmcgcGFzc3dvcmQgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgInBhc3N3b3JkIik7CQkKU3RyaW5nIGxvY2FsRGlyU3Ry
ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJsb2NhbERpciIpOwpTdHJpbmcgcGF0aFRv
UHJpdmF0ZUtleSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAicHJpdmF0ZUtleUZpbGUi
KTsKU3RyaW5nIHBhc3NQaHJhc2UgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgInBhc3NQ
aHJhc2UiKTsKSURhdGEgaW5Eb2MgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiYXV0aCIg
KTsKCi8vIHByb2Nlc3MKCmlmIChyZXBvICE9IG51bGwpIHsKCWlmICh1cmkuZW5kc1dpdGgoIi8i
KSkKCQl1cmkgKz0gcmVwbyArICIuZ2l0IjsKCWVsc2UKCQl1cmkgKz0gIi8iICsgcmVwbyArICIu
Z2l0IjsKfQoKRmlsZSBsb2NhbERpciA9IG5ldyBGaWxlKGxvY2FsRGlyU3RyKTsKCmlmICghbG9j
YWxEaXIuZXhpc3RzKCkpIHsKCWxvY2FsRGlyLm1rZGlycygpOwp9IGVsc2UgaWYgKCFsb2NhbERp
ci5pc0RpcmVjdG9yeSgpKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQnVpbGREaXIg
bXVzdCBiZSBhIGRpcmVjdG9yeTogIiArIGxvY2FsRGlyU3RyKTsKfSBlbHNlIHsKCQoJU3lzdGVt
Lm91dC5wcmludGxuKCJEZWxldGUgZXhpc3RpbmcgZGlyZWN0b3J5ICIgKyBsb2NhbERpclN0cik7
CgoJZGVsZXRlRGlyKGxvY2FsRGlyKTsKCQoJbG9jYWxEaXIubWtkaXIoKTsKfQoJCQpTeXN0ZW0u
b3V0LnByaW50bG4oIkNsb25pbmcgZnJvbSAiICsgdXJpKTsKCkNsb25lQ29tbWFuZCBjID0gbmV3
IENsb25lQ29tbWFuZCgpOwoKaWYgKHBhdGhUb1ByaXZhdGVLZXkgIT0gbnVsbCkgewoJCQkgCgkg
aWYgKHVyaS5zdGFydHNXaXRoKCJodHRwIikpIHsKCgoJCS8vIGlucHV0CgkJSURhdGEgaW5wdXQg
PSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7CgkJSURhdGFDdXJzb3IgaW5wdXRDdXJzb3IgPSBpbnB1
dC5nZXRDdXJzb3IoKTsKCQlJRGF0YVV0aWwucHV0KCBpbnB1dEN1cnNvciwgInVybCIsIHVyaSAp
OwoJCWlucHV0Q3Vyc29yLmRlc3Ryb3koKTsKCgkJLy8gb3V0cHV0CgkJSURhdGEgCW91dHB1dCA9
IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKCQl0cnl7CgkJCW91dHB1dCA9IFNlcnZpY2UuZG9JbnZv
a2UoICJ3eC5wYWNrYWdlcy5tYW5hZ2VyLl9wcml2LnRvb2xzIiwgInNwbGl0VXJsIiwgaW5wdXQg
KTsKCQl9Y2F0Y2goIEV4Y2VwdGlvbiBlKXt9CgkJSURhdGFDdXJzb3Igb3V0cHV0Q3Vyc29yID0g
b3V0cHV0LmdldEN1cnNvcigpOwoJCVN0cmluZwlvd25lciA9IElEYXRhVXRpbC5nZXRTdHJpbmco
IG91dHB1dEN1cnNvciwgIm93bmVyIiApOwoJCXJlcG8gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBv
dXRwdXRDdXJzb3IsICJyZXBvIiApOwoJCVN0cmluZwlyZXBvSG9zdCA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoIG91dHB1dEN1cnNvciwgInJlcG9Ib3N0IiApOwoJCW91dHB1dEN1cnNvci5kZXN0cm95
KCk7CgoJICAgICAKCSAgICAgdXJpID0gImdpdEAiICsgcmVwb0hvc3QgKyAiOiIgKyBvd25lciAr
ICIvIiArIHJlcG8gKyAiLmdpdCI7CgkgICAgIAoJCSBjLnNldFVSSSh1cmkpOwoKCQlTeXN0ZW0u
b3V0LnByaW50bG4oIk5vcGUsIG5vdyBjbG9uaW5nIGZyb20gIiArIHVyaSk7CgkJCgkJSm91cm5h
bExvZ2dlci5sb2coNCw5MCwzLCJbV1BNXSIsICJTZWxlY3RlZCBHaXRodWIgY2xvbmUgVVJJOiAi
ICsgdXJpKTsKCgkgfSBlbHNlIHsKCQljLnNldFVSSSh1cmkpOwoJIH0KCSAKCSAvL2Muc2V0VHJh
bnNwb3J0Q29uZmlnQ2FsbGJhY2soc3NoQ2FsbGJhY2socGF0aFRvUHJpdmF0ZUtleSkpOwoJIAoJ
IGMuc2V0VHJhbnNwb3J0Q29uZmlnQ2FsbGJhY2soCgkJCSB0cmFuc3BvcnQgLT4gewoJCQkgICBp
Zih0cmFuc3BvcnQgaW5zdGFuY2VvZiBTc2hUcmFuc3BvcnQpIHsKCQkJICAgICBTc2hUcmFuc3Bv
cnQgc3NoVHJhbnNwb3J0ID0gKFNzaFRyYW5zcG9ydCkgdHJhbnNwb3J0OwoJCQkgICAgIC8vIFNl
dCBwYXNzcGhyYXNlIHVzaW5nIGEgQ3VzdG9tQ3JlZGVudGlhbHNQcm92aWRlcgoJCQkgICAgIHNz
aFRyYW5zcG9ydC5zZXRDcmVkZW50aWFsc1Byb3ZpZGVyKG5ldyBDdXN0b21DcmVkZW50aWFsUHJv
dmlkZXIocGFzc1BocmFzZSkpOwoJCQkgICAgIC8vIFByb3ZpZGUgcHJpdmF0ZSBrZXkgdG8gYEN1
c3RvbVNzaFNlc3Npb25GYWN0b3J5YAoJCQkgICAgIFNzaFNlc3Npb25GYWN0b3J5IHNzaEZhY3Rv
cnkgPSBuZXcgQ3VzdG9tU3NoU2Vzc2lvbkZhY3RvcnkocGF0aFRvUHJpdmF0ZUtleSk7CgkJCSAg
ICAgc3NoVHJhbnNwb3J0LnNldFNzaFNlc3Npb25GYWN0b3J5KHNzaEZhY3RvcnkpOwoKCQkJICAg
fQoJfSk7Cgp9IGVsc2UgaWYgKGluRG9jICE9IG51bGwpIHsKCUlEYXRhQ3Vyc29yIGluRG9jQ3Vy
c29yID0gaW5Eb2MuZ2V0Q3Vyc29yKCk7CglTdHJpbmcgYXV0aFR5cGUgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKCBpbkRvY0N1cnNvciwgInR5cGUiICk7CQkJCglpbkRvY0N1cnNvci5kZXN0cm95KCk7
CgkKCUNyZWRlbnRpYWxzUHJvdmlkZXIgY3JlZHNQcm92aWRlciA9IG51bGw7CgkKCWlmICgiYmVh
cmVyIi5lcXVhbHNJZ25vcmVDYXNlKGF1dGhUeXBlKSkgewoJCVN0cmluZyB0b2tlbiA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoaW5Eb2NDdXJzb3IsICJ0b2tlbiIpOwkJCQkKCQljcmVkc1Byb3ZpZGVy
ID0gbmV3IFVzZXJuYW1lUGFzc3dvcmRDcmVkZW50aWFsc1Byb3ZpZGVyKHRva2VuLCB0b2tlbik7
CgkJSm91cm5hbExvZ2dlci5sb2coNCw5MCwzLCJbV1BNXSIsIFN0cmluZy5mb3JtYXQoIlNlbGVj
dGVkIEdpdGh1YiBBcHAgYXV0aGVudGljYXRpb246ICVzICVzIiwgdXJpLCAiKiIpKTsKCQkKCX0g
ZWxzZSB7CgkJdXNlciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaW5Eb2NDdXJzb3IsICJ1c2VyIik7
CgkJcGFzc3dvcmQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGluRG9jQ3Vyc29yLCAicGFzcyIpOwoJ
CWlmICh1c2VyICE9IG51bGwgJiYgIXVzZXIuZXF1YWxzKCJudWxsIikpIHsKCQkJY3JlZHNQcm92
aWRlciA9IG5ldyBVc2VybmFtZVBhc3N3b3JkQ3JlZGVudGlhbHNQcm92aWRlcih1c2VyLCBwYXNz
d29yZCk7CgkJCUpvdXJuYWxMb2dnZXIubG9nKDQsOTAsMywiW1dQTV0iLCBTdHJpbmcuZm9ybWF0
KCJTZWxlY3RlZCBHaXRodWIgY3JlZHM6ICVzICVzICVzIiwgdXJpLCB1c2VyLCAiKiIpKTsKCgkJ
fQkJCQkKCX0KCWMuc2V0Q3JlZGVudGlhbHNQcm92aWRlcihjcmVkc1Byb3ZpZGVyKTsKCWMuc2V0
VVJJKHVyaSk7Cn0gZWxzZSB7CgljLnNldFVSSSh1cmkpOwp9CgovL2Muc2V0Q2xvbmVTdWJtb2R1
bGVzKHRydWUpOwoKaWYgKHRhZyAhPSBudWxsKSB7CgljLnNldEJyYW5jaCh0YWcpOwp9CgpjLnNl
dERpcmVjdG9yeShsb2NhbERpcik7Cgp0cnkgewoJYy5jYWxsKCk7CgkJCQkKfSBjYXRjaCAoSW52
YWxpZFJlbW90ZUV4Y2VwdGlvbiBlKSB7CgllLnByaW50U3RhY2tUcmFjZSgpOwoJdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oIkludmFsaWQgR0lUIHNvdXJjZTogIiArIGUuZ2V0TWVzc2FnZSgp
KTsKfSBjYXRjaCAoVHJhbnNwb3J0RXhjZXB0aW9uIGUpIHsKCWUucHJpbnRTdGFja1RyYWNlKCk7
Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiR290IGFuIGV4Y2VwdGlvbiBjb25uZWN0aW5n
IHRvIEdJVCByZXBvOiAiICsgZS5nZXRNZXNzYWdlKCkpOwp9IGNhdGNoIChKR2l0SW50ZXJuYWxF
eGNlcHRpb24gZSkgewoJZS5wcmludFN0YWNrVHJhY2UoKTsKCXRocm93IG5ldyBTZXJ2aWNlRXhj
ZXB0aW9uKCJHb3QgYW4gaW50ZXJuYWwgZXhjZXB0aW9uIGZyb20gR0lUIEFQSTogVGhpcyBtaWdo
dCBiZSBjYXVzZWQgYnkgYSBiYWRseSByZWZlcmVuY2VkIHN1Ym1vZHVsZSwgIiArIGUuZ2V0TWVz
c2FnZSgpKTsKfSBjYXRjaCAoR2l0QVBJRXhjZXB0aW9uIGUpIHsKCWUucHJpbnRTdGFja1RyYWNl
KCk7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiR290IGFuIGV4Y2VwdGlvbiBmcm9tIEdJ
VCBBUEk6ICIgKyBlLmdldE1lc3NhZ2UoKSk7Cn0KCi8vIHBpcGVsaW5lIG91dAoKY3Vyc29yLmRl
c3Ryb3koKTsKCQoJCgkKCQoJCg==</value>
</Values>
