<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invokeAsync</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBzZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1
cnNvciwgInNlcnZpY2UiKTsKCklEYXRhIHAgPSBJRGF0YVV0aWwuZ2V0SURhdGEocGlwZWxpbmVD
dXJzb3IsICJwaXBlbGluZSIpOwoKLyppZiAocCA9PSBudWxsKSB7CglwID0gSURhdGFGYWN0b3J5
LmNyZWF0ZSgpOwp9Ki8KCmludCBpbmRleCA9IHNlcnZpY2UuaW5kZXhPZigiOiIpOwpTdHJpbmcg
aWZjID0gIiI7CgppZiAoaW5kZXggIT0gLTEpIHsKCWlmYyA9IHNlcnZpY2Uuc3Vic3RyaW5nKDAs
IGluZGV4KTsKCXNlcnZpY2UgPSBzZXJ2aWNlLnN1YnN0cmluZyhpbmRleCsxKTsKfQoKU2Vydmlj
ZS5kb1RocmVhZEludm9rZShpZmMsIHNlcnZpY2UsIHApOwoKLy8gcGlwZWxpbmUgb3V0Cgk=</value>
</Values>
